sudo: required
services:
  - docker

before_install:
  - docker build -t jurgello/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jurgello/docker-react npm run test -- --coverage 
